matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      install:
        - sudo apt update
        - sudo apt install sshpass 
        - pip3 install -r requirements.txt
      before_script:
        - bash functional_testing/Openvcloud/tools/travis_script.sh before
      script:
        - bash functional_testing/Openvcloud/tools/travis_script.sh test
      after_script:
        - bash functional_testing/Openvcloud/tools/travis_script.sh after
      after_failure:
        - bash functional_testing/Openvcloud/tools/travis_script.sh after
