language: python
dist: trusty
sudo: true
if: type IN (api, cron)
install: 
  - sudo apt install sshpass -y
  - curl -s https://install.zerotier.com/ | sudo bash

jobs:
  include:
  - stage: Prepare
    script: bash functional_testing/Openvcloud/tools/travis_script.sh setup
      
  - stage: Tests
    python: 2.7
    script: bash functional_testing/Openvcloud/tools/travis_script.sh acl
  
  - stage: Tests
    python: 2.7
    script: bash functional_testing/Openvcloud/tools/travis_script.sh ovc

  - stage: Tests
    python: 2.7
    script: bash functional_testing/Openvcloud/tools/travis_script.sh portal

  - stage: Tests
    python: 3.5
    script: bash functional_testing/Openvcloud/tools/travis_script.sh restful