language: python
sudo: true
dist: trusty
jobs:
  include:
  - python: "2.7"
    env: 
    - testsuite-title=ACL
    - testsuite-home-dir=G8_testing/functional_testing/Openvcloud
    - testsuite-run-dir=${acl_testsuite_dir}

  - python: "2.7"
    env:
    - testsuite-title=OVC 
    - testsuite-home-dir=G8_testing/functional_testing/Openvcloud
    - testsuite-run-dir=${ovc_testsuite_dir}

install:
  - sudo apt install git

script: bash functional_testing/Openvcloud/tools/travis_script.sh test
before_script: bash functional_testing/Openvcloud/tools/travis_script.sh before
after_script: bash functional_testing/Openvcloud/tools/travis_script.sh after