language: python
sudo: true
dist: trusty
matrix:
  include:
    - python: "2.7"
      script: bash functional_testing/Openvcloud/tools/travis_script.sh test acl ${acl_testsuite_dir}

    - python: "2.7"
      script: bash functional_testing/Openvcloud/tools/travis_script.sh test ovc ${ovc_testsuite_dir}

    - python: "3.5"
      script: bash functional_testing/Openvcloud/tools/travis_script.sh test portal ${portal_testsuite_dir}

install:
  - sudo apt install git sshpass -y
  - curl -s https://install.zerotier.com/ | sudo bash

before_script: bash functional_testing/Openvcloud/tools/travis_script.sh before
after_script: bash functional_testing/Openvcloud/tools/travis_script.sh after