matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 2.7
      install:
        - sudo apt update
        - sudo apt install sshpass 
        - curl -s https://install.zerotier.com/ | sudo bash
      before_script:
        - bash functional_testing/Openvcloud/tools/travis_script.sh before
      script:
        - bash functional_testing/Openvcloud/tools/travis_script.sh test
      after_script:
        - bash functional_testing/Openvcloud/tools/travis_script.sh after
      after_failure:
        - bash functional_testing/Openvcloud/tools/travis_script.sh after
